### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by rabernat** [CumulusDS/get-yaml-paths-action#2]
Thanks for sharing this action. It looks very useful for me. I want to parse a yaml config file in my repo and use the results inside a workflow.

My workflow is here: https://github.com/pangeo-gallery/example-gallery/blob/master/.github/workflows/binderbot.yaml#L26

My step looks like this
```yaml
      - name: parse config
        uses: CumulusDS/get-yaml-paths-action@v0.0.3
        with:
          file: pangeo-gallery.yaml
          gallery_repository: gallery_repository
          binder_url: binder_url
          binder_repo: binder_repo
          binder_ref: binder_ref
          binderbot_target_branch: binderbot_target_branch
```

And the file `pangeo-gallery.yaml` looks like this (lives at the root directory of my repo)
```yaml
name: Example Gallery
description: >-
  An example gallery of notebooks used for debugging the Pangeo Gallery
  infrastructure.
gallery_repository: pangeo-gallery/pangeo-gallery
binder_url: "http://mybinder.org"
binder_repo: binder-examples/requirements
binder_ref: master
binderbot_target_branch: binderbot-built
```

When the workflow [runs](https://github.com/pangeo-gallery/example-gallery/runs/531270412?check_suite_focus=true), I get the following error

``` 
Run CumulusDS/get-yaml-paths-action@v0.0.3
  with:
    file: pangeo-gallery.yml
    gallery_repository: gallery_repository
    binder_url: binder_url
    binder_repo: binder_repo
    binder_ref: binder_ref
    binderbot_target_branch: binderbot_target_branch
(node:2602) UnhandledPromiseRejectionWarning: TypeError: (e || "").replace is not a function
    at /home/runner/work/_actions/CumulusDS/get-yaml-paths-action/v0.0.3/dist/main.js:1:11987
    at a.toString (/home/runner/work/_actions/CumulusDS/get-yaml-paths-action/v0.0.3/dist/main.js:1:12049)
    at s (/home/runner/work/_actions/CumulusDS/get-yaml-paths-action/v0.0.3/dist/main.js:1:11416)
    at Object.t.issue (/home/runner/work/_actions/CumulusDS/get-yaml-paths-action/v0.0.3/dist/main.js:1:11476)
    at c (/home/runner/work/_actions/CumulusDS/get-yaml-paths-action/v0.0.3/dist/main.js:1:5323)
    at Object.t.setFailed (/home/runner/work/_actions/CumulusDS/get-yaml-paths-action/v0.0.3/dist/main.js:1:6064)
    at /home/runner/work/_actions/CumulusDS/get-yaml-paths-action/v0.0.3/dist/main.js:1:182721
(node:2602) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2602) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Unfortunately I don't really know Node.js and don't know how to debug the error. Any advice would be much appreciated.

Thanks again for sharing this action.

**Comment by joshuanapoli** [comment]
Thanks for posting the issue; I'll take a look at the problem.

**Comment by rabernat** [comment]
Thanks for your quick reply!

Just as a follow-up, I simplified this to use the example from the docs. My [entire workflow](https://github.com/pangeo-gallery/example-gallery/runs/531314930?check_suite_focus=true) is now just

```yaml
name: Test YAML Parser
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: parse config
        uses: CumulusDS/get-yaml-paths-action@v0.0.3
        with:
          file: file.yaml
          bar: foo.bar
          providerStage: provider.stage
      - name: show outputs
        run: echo ${{ steps.parse_config.outputs.bar }}
```

With `file.yaml` identical to the example. I get the same error.
