### ISSUE TITLE
Load Array Values

### ISSUE THREAD

**Issue by timbmg** [CumulusDS/get-yaml-paths-action#32]
I have a yaml file similar to this:
```yaml
foo:
  - bar: "hello"
  - bar: "world"
```
I would like to read the `bar` values such that my output is something like: `["hello", "world"]`
