### ISSUE TITLE
Read float number from yaml

### ISSUE THREAD

**Issue by asemlucben** [CumulusDS/get-yaml-paths-action#61]
Hi, i have an input YAML file like this:
```yaml
Project:
 FormatVersion: 1
 ProductVersion: 1.0
```
and I configured my action like this:
```yaml
- name: Read Product Version
  id: yaml-data
  uses: CumulusDS/get-yaml-paths-action@v1.0.1
  with:
    file: './${{ github.event.repository.name }}.yaml'
    data: Project.ProductVersion
```
But when I access the variable `${{ steps.yaml-data.outputs.data }}` I get `1` and not `1.0` is there any way to fix that?

**Comment by joshuanapoli** [comment]
When the input YAML represents a number like 1 or 1.0, it is parsed into a JavaScript Number, and in JavaScript, `1 === 1.0`. The fact that the original YAML had a decimal point is lost.

You might be able to make the ProductVersion a string. You'll have to do this anyway if you really have a semver or need more than two version number parts. For example:

```yaml
Project:
 FormatVersion: 1
 ProductVersion: "1.0"
```

Using quotes makes the YAML value a string type, and the whole string should pass through to the output and do what you want.
